# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638ad2d6ec8cf1cc4f151db322b1ad6bfeaedb29124268d59af99d5e62bcbfe97d75213d15daaf8d78a97f41b1df8fc90f77b0a7de5bf20c70b6d46536e7b38e

test:
  secret_key_base: dd964c5b5921403166cc6b2853e318863c12063990fc4cce01115a615c87185e11353a89f5414502de8071c0b18201cc036b110a2db7e5bd586d3e43f6e833e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
